#!/usr/bin/env bash

set -Eeuo pipefail

make

mkdir -p out/1 out/2
rm -rf out/1/* out/2/*

./out/minicc main.c | ./scripts/asm-fmt > out/1/main.s
clang -g -o out/1/minicc out/1/main.s
./out/1/minicc main.c | ./scripts/asm-fmt > out/2/main.s
diff -u out/1/main.s out/2/main.s
echo "PASS"
