#!/usr/bin/env bash

set -Eeuo pipefail

run() {
    echo "$@"
    eval "$@"
}

run "rm -rf out"
run "mkdir -p out/1 out/2"

# stage 0: use host toolchain
make

# stage 1: self-compile with stage 0 compiler
run "./out/0/smolcc < src/main.c | ./scripts/asm-fmt > out/1/main.s"
run "cc -nostdlib -o out/1/smolcc out/1/main.s src/sys.s"

# stage 2: self-compile with stage 1 compiler
run "./out/1/smolcc < src/main.c | ./scripts/asm-fmt > out/2/main.s"
run "diff -u out/1/main.s out/2/main.s"
run "cc -nostdlib -o out/2/smolcc out/2/main.s src/sys.s"

echo "PASS"
