#!/usr/bin/env bash

set -Eeuo pipefail

usage() {
    echo "Usage: $0 [options] <file.c>"
}

help() {
    usage
    cat <<EOF
Options:
    -S         Only run compilation steps
    -o <file>  Specify output file
    -c         Only run compilation and assembly steps
    -h         Show this help message
EOF
}

output_file=
stop_after_asm=false
stop_after_obj=false

while getopts "hSco:" opt; do
    case $opt in
        S) stop_after_asm=true ;;
        o) output_file="$OPTARG" ;;
        c) stop_after_obj=true ;;
        h) help; exit 0 ;;
        *) usage; exit 1 ;;
    esac
done

shift $((OPTIND - 1))

if [[ $# -ne 1 ]]; then
    usage
    exit 1
fi

source_file="$1"

if [[ -z "$output_file" ]]; then
    asm_file="${source_file%.c}.s"
    obj_file="${source_file%.c}.o"
    exe_file=a.out
else
    if [[ $stop_after_asm == true ]]; then
        asm_file="$output_file"
    else
        asm_file="${output_file%.o}.s"
    fi
    if [[ $stop_after_obj == true ]]; then
        obj_file="$output_file"
    else
        obj_file="${output_file%.o}.o"
    fi
    exe_file="${output_file}"
fi

if [[ "${MINICC_SKIP_MAKE:-0}" != "1" ]]; then
    env MAKEFLAGS="${MAKEFLAGS:+$MAKEFLAGS }--silent" make
fi

./out/minicc "$source_file" | ./scripts/asm-fmt > "$asm_file"
if [[ $stop_after_asm == true ]]; then
    exit 0
fi

cc "$asm_file" -g -c -o "$obj_file"
if [[ $stop_after_obj == true ]]; then
    exit 0
fi

cc "$obj_file" -g -o "$exe_file"
