#!/usr/bin/env bash

set -Eeuo pipefail

script_dir=$(dirname "$(readlink -f "$0")")

usage() {
    echo "Usage: $0 [options] <file.c>"
}

help() {
    usage
    cat <<EOF
Options:
    -S         Only run compilation steps
    -o <file>  Specify output file
    -c         Only run compilation and assembly steps
    -v         Show version information
    -h         Show this help message
EOF
}


version_info=$script_dir/smolcc.version
smolcc1=$script_dir/smolcc1
asm_fmt=$script_dir/asm-fmt
crt_o=$script_dir/../lib/crt.o
libc_a=$script_dir/../lib/libc.a

version() {
    if [[ -f "$version_info" ]]; then
        cat "$version_info"
    else
        echo "smolcc (version information not found)"
    fi
}

cc=cc
output_file=
stop_after_asm=false
stop_after_obj=false

while getopts "hSco:l:v" opt; do
    case $opt in
        S) stop_after_asm=true ;;
        o) output_file="$OPTARG" ;;
        c) stop_after_obj=true ;;
        v) version; exit 0 ;;
        h) help; exit 0 ;;
        *) usage; exit 1 ;;
    esac
done

shift $((OPTIND - 1))

if [[ $# -ne 1 ]]; then
    usage
    exit 1
fi

source_file="$1"

if [[ -z "$output_file" ]]; then
    asm_file="${source_file%.c}.s"
    obj_file="${source_file%.c}.o"
    exe_file=a.out
else
    if [[ $stop_after_asm == true ]]; then
        asm_file="$output_file"
    else
        asm_file="${output_file%.o}.s"
    fi
    if [[ $stop_after_obj == true ]]; then
        obj_file="$output_file"
    else
        obj_file="${output_file%.o}.o"
    fi
    exe_file="${output_file}"
fi

"$smolcc1" \
    < "$source_file" \
    2> >(sed "s|<stdin>:|$source_file:|g" >&2) \
    | sed "s|<stdin>:|$source_file:|g" \
    | "$asm_fmt" > "$asm_file"
if [[ $stop_after_asm == true ]]; then
    exit 0
fi

"$cc" "$asm_file" -g -c -o "$obj_file"
if [[ $stop_after_obj == true ]]; then
    exit 0
fi

"$cc" -nostdlib "$crt_o" "$obj_file" -g -o "$exe_file" "$libc_a"
