#!/usr/bin/env bash

set -Eeuo pipefail

script_dir=$(dirname "$(readlink -f "$0")")
smolcc="$script_dir/../build/dist/bin/smolcc"

usage() {
    echo "Usage: $0 [options] <file.c>"
}

help() {
    usage
    cat <<EOF
Options:
    -v         Enable verbose output
    -h         Show this help message
EOF
}

arg_error() {
    echo "Error: $1"
    usage
    exit 1
}

run() {
    if $verbose; then
        echo "$*"
    fi
    "$@"
}

source_file=
verbose=false

while [[ "$#" -gt 0 ]]; do
    case "$1" in
    -h | --help)
        help
        exit 0
        ;;
    -v)
        verbose=true
        shift
        ;;
    --)
        shift
        break
        ;;
    *)
        if [[ -z "$source_file" ]]; then
            source_file="$1"
        else
            arg_error "Unexpected argument: $1"
        fi
        shift
        ;;
    esac
done

if [[ -z "$source_file" ]]; then
    arg_error "No source file specified"
fi

if [[ ! -x "$smolcc" ]]; then
    arg_error "Compiler not found at $smolcc."
fi

v_flg=()
if $verbose; then
    v_flg+=("-v")
fi

tmp_root="${TMPDIR:-/tmp}"
build_dir=$(mktemp -d "${tmp_root%/}/smolcc-run.XXXXXX")
trap 'rm -rf "$build_dir"' EXIT

output_file="$build_dir/a.out"

run "$smolcc" "${v_flg[@]}" -o "$output_file" "$source_file"

run "$output_file" "$@"
