#!/usr/bin/env bash

set -Eeuo pipefail

usage() {
    echo "Usage: $0 [options] <file.c>"
}

help() {
    usage
    cat <<EOF
Options:
    -h         Show this help message
EOF
}

arg_error() {
    echo "Error: $1"
    usage
    exit 1
}

smolcc=${SMOLCC:-smolcc}
source_file=

while [[ "$#" -gt 0 ]]; do
    case "$1" in
        -h|--help)
        help; exit 0 ;;
        --) shift; break ;;
        *)
        if [[ -z "$source_file" ]]; then
            source_file="$1"
        else
            arg_error "Unexpected argument: $1"
        fi
        shift ;;
    esac
done

if [[ -z "$source_file" ]]; then
    arg_error "No source file specified"
fi

tmp_root="${TMPDIR:-/tmp}"
build_dir=$(mktemp -d "${tmp_root%/}/smolcc-run.XXXXXX")
trap 'rm -rf "$build_dir"' EXIT

output_file="$build_dir/a.out"

"$smolcc" -o "$output_file" "$source_file"

"$output_file" "$@"
